version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest-alpine
    container_name: clickhouse
    privileged: true
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    environment:
      TZ: "UTC"
      CLICKHOUSE_DB: "fox_game"
      CLICKHOUSE_USER: "fox"
#      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ""
      CLICKHOUSE_PASSWORD: "fox^123456"
