version: '3'

services:
  planka:
    image: ghcr.io/plankanban/planka:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./data/user-avatars:/app/public/user-avatars
      - ./data/project-background-images:/app/public/project-background-images
      - ./data/attachments:/app/private/attachments
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`plan.hawtech.cn`)"
      - "traefik.http.services.static.loadbalancer.server.port=1337"
    environment:
      - BASE_URL=http://plan.hawtech.cn
      - TRUST_PROXY=0
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=f7e960fd9cd3fffa5fb2fdd9009404c720bb66b7b17bc78665a1167c1bdc7a6d83a6735ed53e857514bc1bddb7d30c320478962285950be046c4b514d800b1ad

      # related: https://github.com/knex/knex/issues/2354
      # As knex does not pass query parameters from the connection string we
      # have to use environment variables in order to pass the desired values, e.g.
      # - PGSSLMODE=<value>

      # Configure knex to accept SSL certificates
      # - KNEX_REJECT_UNAUTHORIZED_SSL_CERTIFICATE=false
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust