api:
  insecure: true
  dashboard: true
  debug: true

providers:
  providersThrottleDuration: 30s
  docker:
    exposedByDefault: false
  file:
    directory: /conf/conf.d
    watch: true
    filename: "*.yml"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true

  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: "lhj168os@gmail.com"
      storage: "/data/acme.json"
      httpChallenge:
        entryPoint: web

log:
  level: INFO
  filePath: /data/logs/traefik.log