version: '3.8'

services:
  frpc:
    image: snowdreamtech/frp
    container_name: frpc
    privileged: true
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./frpc.ini:/etc/frp/frpc.ini  # 替换为你的frpc.ini配置文件路径
    command: frpc -c /etc/frp/frpc.ini