version: "3.8"
# https://github.com/brokercap/Bifrost
services:
  bifrost:
    image: jayos/bifrost:latest
    container_name: bifrost
    restart: always
    ports:
      - "21036:21036"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/etc:/linux/etc
      - ./data/data:/data
      - ./data/logs:/logs