version: "3"

networks:
  traefik-network:
    external: true

services:
  gitea:
    image: gitea/gitea:1.19
    container_name: gitea
#    environment:
#      - USER_UID=1000
#      - USER_GID=1000
    restart: always
    networks:
      - traefik-network
    ports:
      - "3000:3000"
      - "22:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.services.gitea.loadbalancer.server.scheme=http"
      - "traefik.http.routers.gitea.rule=Host(`git.hawtech.cn`)"
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
