version: "3"
services:
  mindoc:
    image: neosmemo/memos:latest
    container_name: memos
    privileged: true
    restart: always
    ports:
      - 5230:5230
    volumes:
      - ./data:/var/opt/memos
    environment:
      TZ: Asia/Shanghai
