version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    privileged: true
    restart: always
    command:
      - "--configfile=/conf/traefik.yml"
    networks:
      - traefik-network
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.rule=Host(`traefik.hawtech.cn`)"
      - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf:/conf
      - ./data:/data
      - ./data/acme:/etc/traefik/acme

networks:
  traefik-network:
    external: true