version: '3.8'

services:
  nps:
    image: ffdfgdfg/nps
    container_name: nps
    privileged: true
    restart: always
    network_mode: "host"
    volumes:
      - ./conf:/conf  # 挂载配置文件目录
    command: server

