version: '3.1'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: always
    container_name: jenkins
    privileged: true # 特权模式
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/var/jenkins_home  # jenkins数据目录