version: '3.1'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: always
    network_mode: "host"
    hostname: jenkins
    container_name: jenkins
    privileged: true # 特权模式
    user: root
    environment:
     TZ: Asia/Shanghai
    volumes:
    - ./data:/var/jenkins_home  # jenkins数据目录
