version: "3.8"

networks:
  traefik-network:
    external: true

services:
  remark:
    # remove the next line in case you want to use this docker-compose separately
    # as otherwise it would complain for absence of Dockerfile
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: "remark42"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    networks:
      - traefik-network
    # uncomment to expose directly (no proxy)
    ports:
      - "8080:8080"
      - "8443:8443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=8080"
      - "traefik.http.services.gitea.loadbalancer.server.scheme=http"
      - "traefik.http.routers.gitea.rule=Host(`remark.hawtech.cn`)"
    environment:
      - REMARK_URL=remark.hawtech.cn
      - SECRET
      - DEBUG=true
      - AUTH_ANON=true
      - AUTH_EMAIL_ENABLE=true
      - AUTH_GOOGLE_CID
      - AUTH_GOOGLE_CSEC
      - AUTH_GITHUB_CID
      - AUTH_GITHUB_CSEC
      - AUTH_FACEBOOK_CID
      - AUTH_FACEBOOK_CSEC
      - AUTH_DISQUS_CID
      - AUTH_DISQUS_CSEC
      - ADMIN_PASSWD=jager.666168
      # Enable it only for the initial comment import or for manual backups.
      # Do not leave the server running with the ADMIN_PASSWD set if you don't have an intention
      # to keep creating backups manually!

    volumes:
      - ./data:/srv/var