version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    privileged: true
    restart: always
#    network_mode: "host"
#    hostname: mysql
    networks:
      fox-net:
        aliases:
          - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/mysql:/etc/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ./data:/var/lib/mysql
    environment:
      TZ: "UTC"
      MYSQL_ROOT_PASSWORD: 123456

networks:
  fox-net:
    external: true
