version: "3"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    privileged: true
    restart: always
    networks:
      - traefik-network
    ports:
      - 5230:5230
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.memos.loadbalancer.server.port=5230"
      - "traefik.http.services.memos.loadbalancer.server.scheme=http"
      - "traefik.http.routers.memos.rule=Host(`memos.hawtech.cn`)"
    volumes:
      - ./data:/var/opt/memos
    environment:
      TZ: Asia/Shanghai
