version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    privileged: true
    restart: always
    ports:
      - "6379:6379"
#    command: redis-server /conf.d/redis.conf --appendonly yes
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - ./data:/data
#      - ./conf.d:/conf.d
#      - ./logs:/logs
