version: "3.8"

services:
  redis:
    image: redis:5-alpine
    container_name: fox-redis
    privileged: true
    user: root
    restart: always
    network_mode: "host"
    hostname: fox-redis
    command: redis-server /conf.d/redis.conf --appendonly yes
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
      - ./conf.d:/conf.d
      - ./logs:/logs
